### ISSUE TITLE
NPM release to PR #16

### ISSUE THREAD

**Issue by fsmaia** [ForbesLindesay/tar-pack#18]
Hi there,

Congratulations for the lib, it has been extremely useful in a lot of scenarios.

However, the `fromBase` flag, from PR #16 still wasn't published in NPM.

Is there any specific reason? Otherwise could you publish it?

May I be helpful somehow?

Thanks so far!

**Comment by es128** [comment]
@fsmaia it appears to have been an oversight on my part, since I said in that PR that I'd take care of publishing. Apologies, working on it now. Thanks for bringing it to my attention.
