### ISSUE TITLE
Bump `once`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [ForbesLindesay/tar-pack#20]
`tar-pack` depends on `once@1.3.3`.  But it also depends on `tar`, which depends on `fstream`, which depends on `rimraf`, which depends on `glob`, which depends on `once@1.4.0`.  So two versions of `once` are required when using `tar-pack`.
I can submit a PR for this if you would like.

**Comment by billyjanitsch** [comment]
#19 would resolve this.
